services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
    tty: true
    stdin_open: true